# Generated by Django 4.0.6 on 2022-08-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0003_alter_comment_comment_date_alter_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(verbose_name='date commented'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(verbose_name='posted on'),
        ),
    ]
