# Generated by Django 4.0.6 on 2022-08-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0006_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
