# Generated by Django 4.0.6 on 2022-08-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0010_comment_user_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
