# Generated by Django 4.0.6 on 2022-08-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0012_alter_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.CharField(max_length=250),
        ),
    ]
