# Generated by Django 4.0.6 on 2022-08-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0013_alter_post_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(max_length=250),
        ),
    ]
